image:
  repository: rancher/fleet-agent
  tag: dev

# Labels to add to the cluster upon registration only. They are not added after the fact.
#labels:
#  foo: bar
# The client ID of the cluster to associate with
clientID: ""

# Number of simulator to run
simulators: 1
