bootstrap:
  enabled: true

global:
  cattle:
    systemDefaultRegistry: "ghcr.io"

nodeSelector:
  kubernetes.io/os: os2

tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    operator: "Equal"
    value: "true"
    effect: NoSchedule

priorityClassName: "prio1"

gitops:
  enabled: true

metrics:
  enabled: true

debug: true
debugLevel: 4
propagateDebugSettingsToAgents: true
disableSecurityContext: true

cpuPprof:
  period: "60s"
  volumeConfiguration:
    hostPath:
      path: /tmp/pprof
      type: DirectoryOrCreate

migrations:
  clusterRegistrationCleanup: true

leaderElection:
  leaseDuration: 30s
  retryPeriod: 10s
  renewDeadline: 25s

controller:
  reconciler:
    workers:
      gitrepo: "1"
      bundle: "1"
      bundledeployment: "1"

extraEnv:
  - name: EXPERIMENTAL_HELM_OPS
    value: "true"

shards:
  - id: shard0
    nodeSelector:
      kubernetes.io/hostname: k3d-upstream-server-0
  - id: shard1
    nodeSelector:
      kubernetes.io/hostname: k3d-upstream-server-1
  - id: shard2
    nodeSelector:
      kubernetes.io/hostname: k3d-upstream-server-2
