site_name: Fleet - GitOps at Scale
repo_url: https://github.com/rancher/fleet
# Set to false for local docs development
strict: true
theme:
  name: material
  palette:
    primary: green
  font:
    text: 'Work Sans'
  logo: 'assets/logo.svg'
  #favicon: 'assets/favicon-32x32.png'
#google_analytics:
plugins:
  - search
  - markdownextradata: {}
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - index.md
  - quickstart.md
  - concepts.md
  - architecture.md
  - examples.md
  - Operator Guide:
    - Installation:
      - Overview: installation.md
      - single-cluster-install.md
      - multi-cluster-install.md
      - uninstall.md
    - Managing Clusters:
      - Registration:
        - cluster-overview.md
        - cluster-tokens.md
        - agent-initiated.md
        - manager-initiated.md
      - cluster-group.md
    - namespaces.md
  - User Guide:
    - Managing Git Repos:
      - gitrepo-add.md
      - gitrepo-structure.md
      - gitrepo-targets.md
extra:
  fleet:
    apiVersion: fleet.cattle.io/v1alpha1
    version: v0.3.0
    helmversion: 0.3.0
