annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>= 1.32.0-0 < 1.35.0-0'
  catalog.cattle.io/namespace: cattle-fleet-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: '>= 2.13.0-0 < 2.14.0-0'
  catalog.cattle.io/release-name: fleet-agent
apiVersion: v2
appVersion: 0.14.0-alpha.4
description: Fleet Agent - GitOps at Scale
icon: https://charts.rancher.io/assets/logos/fleet.svg
name: fleet-agent
version: 0.14.0-alpha.4
