image:
  os: "windows,linux"
  repository: rancher/fleet-agent
  tag: dev

# The public URL of the Kubernetes API server running the Fleet Manager must be set here
# Example: https://example.com:6443
apiServerURL: ""

# The the pem encoded value of the CA of the Kubernetes API server running the Fleet Manager.
# If left empty it is assumed this Kubernetes API TLS is signed by a well known CA.
apiServerCA: ""

# The cluster registration value
token: ""

# Labels to add to the cluster upon registration only. They are not added after the fact.
#labels:
#  foo: bar

# The client ID of the cluster to associate with
clientID: ""

# The namespace of the cluster we are register with
clusterNamespace: ""

# The namespace containing the clusters registration secrets
systemRegistrationNamespace: fleet-clusters-system

# Please do not change the below setting unless you really know what you are doing
internal:
  systemNamespace: fleet-system
  managedReleaseName: fleet-agent

# The nodeSelector and tolerations for the agent deployment
fleetAgent:
  nodeSelector: {}
  tolerations: []
kubectl:
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: cattle.io/os
      operator: "Equal"
      value: "linux"
      effect: NoSchedule
    - key: node.cloudprovider.kubernetes.io/uninitialized
      operator: "Equal"
      value: "true"
      effect: NoSchedule

global:
  cattle:
    systemDefaultRegistry: ""
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2

# Additional env variables in the format key=value
env: {}

# Use this secret to pass values to the fleet agents
# Case usage: https://github.com/variantdev/vals#suported-backends
secret: ""