name: Add issue to project board
# This action could be removed when editing workflow project feature will be enabled.
# Still notify with "Coming soon" flag.
# Until now, that's not possible to specify a column, see https://github.com/actions/add-to-project/issues/71
on:
  issues:
    types:
      - opened
      - transfered

jobs:
  add-to-project:
    name: Add issue to project Rancher/Fleet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/rancher/projects/12
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: area/fleet
