gitjob:
  repository: rancher/gitjob
  tag: ${VERSION}

tekton:
  repository: rancher/tekton-utils
  tag: v0.1.15

global:
  cattle:
    systemDefaultRegistry: ""

# http[s] proxy server
# proxy: http://<username>@<password>:<url>:<port>

# comma separated list of domains or ip addresses that will not use the proxy
noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: cattle.io/os
    operator: "Equal"
    value: "linux"
    effect: NoSchedule

# PriorityClassName assigned to deployment.
priorityClassName: ""

debug: false
