annotations:
  catalog.cattle.io/auto-install: fleet-crd=match
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/experimental: "true"
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>= 1.28.0-0 < 1.34.0-0'
  catalog.cattle.io/namespace: cattle-fleet-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: clusters.fleet.cattle.io/v1alpha1
  catalog.cattle.io/rancher-version: '>= 2.12.0-0 < 2.13.0-0'
  catalog.cattle.io/release-name: fleet
apiVersion: v2
appVersion: 0.13.0-alpha.3-test
description: Fleet Controller - GitOps at Scale
icon: https://charts.rancher.io/assets/logos/fleet.svg
name: fleet
version: 0.13.0-alpha.3-test
