apiVersion: v2
name: fleet-crd
description: Fleet Manager CustomResourceDefinitions
version: 0.0.0
appVersion: 0.0.0
icon: https://charts.rancher.io/assets/logos/fleet.svg
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: fleet-system
  catalog.cattle.io/release-name: fleet-crd
  catalog.cattle.io/os: linux
