name: CI

on:
  schedule:
    - cron:  '0 5 * * *'
  pull_request:
  push:
    branches:
    - 'release/*'

env:
  GOARCH: amd64
  CGO_ENABLED: 0

jobs:
  unit-test:
    runs-on: runs-on,runner=16cpu-linux-x64,mem=16,run-id=${{ github.run_id }}

    steps:
      -
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      -
        name: Set up chart-testing
        uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # v2.3.1
        with:
          version: v3.3.0
      -
        name: Run chart-testing (lint)
        run: ct lint --all --validate-maintainers=false charts/
      -
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      -
        name: unit-test
        run: go test -shuffle=on $(go list ./... | grep -v -e /e2e -e /integrationtests)
      -
        name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      -
        name: integration-tests
        env:
          SETUP_ENVTEST_VER: v0.0.0-20240115093953-9e6e3b144a69
          ENVTEST_K8S_VERSION: 1.28
        run: ./.github/scripts/run-integration-tests.sh
